### ISSUE TITLE
Progress Tracker and Missing Events

### ISSUE THREAD

**Issue by knyghtmare** [knyghtmare/AOI_Rework#4]
# Code to Add
## Prologue
- [x] Movements and effects to further convey the mood of the cutscene
- [x] teleport key characters across the map for the varying scenes (we have 3)
- [x] Scene 1 - Outskirts of the Kalian
- [x] Scene 2 - Inner keep
- [x] Scene 3 - Pre-Exile Scene
- [x] custom sprite for Logalmier
- [x] custom sprite for Dionli

## Scenario 1
- [x] Time Over Event
- [x] Attack and ToD Events
- [x] Goblin Sighted event
- [x] Wolf Rider sighted event
- [x] Patch bug in moveto event which throws in whereever Erlornas steps on which is not at all intended. 
- [x] Balance Scenario as it's a bit way easy on Story Mode and maybe doable in Challenge mode
- [x] Refactor Side 1,2 village capture event so that his dialogues are switching and not sequential

## Scenario 2
- [x] Time Over Event
- [x] Start
- [x] Enemies Defeated
- [x] Balance Scenario

 ## Scenario 3
- [x] Time Over Event
- [x] High Warlord sighted event
- [x] High Warlord slain event
- [x] First slaves encounter event
- [x] High Warlord Sighted event
- [x] High Warlord kills someone event
- [x] make High Warlord even a bigger menace than he already is
- [x] Add a special prison cell for the prisoner leader
- [x] Add dummy leader for prisoner side
- [x] Add a new macro for prisoner side
- [x] Allow Side 6 (prisoners) to free other prisoners.
- [x] Enemies Defeated event
- [x] Adjust enemy defeated event for the cutscene
- [x] saurian sighted event
- [x] ogre sighted
- [x] Start event
- [x] Refactor Side 1,2 village capture event so that his dialogues are switching and not sequential
- [x] Balance Scenario

## Scenario 4 
- [x] Fighting Fatigue event
- [x] Update dialogues on deaths/final wave etc
- [x] troll sighted event
- [x] Concede Defeat Menu Item does not appear 
- [x] Concede Defeat Menu sort of "breaks" the right-click menu with the large icon size.
- [x] Readjust kill counters
- [x] add option to display scenario options
- [x] Revise final wave spawn locations

## Units:
- [x] Fix portrait for Orcish Foreman throwing "Image not Found"
- [x] Add the missing "fist" icon for that Slinger unit
- [x] Add Elven Bard unit
- [x] Description for Elven Poet
- [x] Add a second trait to each character

## Finalise

- [x] Generate POT file for translations
- [x] run wmlindent
- [x] run wmllint
- [x] run wmlscope
- [x] Release Summary and Poster
- [x] Fancy Advertisement

**Comment by knyghtmare** [comment]
I think this list gets bigger and bigger every day.
