### ISSUE TITLE
RoadMap v1.1.0

### ISSUE THREAD

**Issue by knyghtmare** [knyghtmare/AOI_Rework#7]
- [x] two new heroes - Tailendos and (a new one)
- [ ]  a specific artifact item in each scenario (with the flaming sword being the drop of the last scenario)
- [ ] Story Mode
- [x] #16
- [ ] Refinement of existing scenarios/cutscenes
- [x] custom campaign icon
- [ ] Equip/De-equip System from WoL (it's available but it's experimental)
- [x] Optimise SP mode for 1 player and keep Mp mode for 2 players
- [x] #19
- [x] #20
- [ ] #22

**Comment by knyghtmare** [comment]
![AOI PROMO_alt](https://user-images.githubusercontent.com/5283677/154074958-680dc12e-c74c-4d36-ad95-e6e34eb6f174.jpg)
